### ISSUE TITLE
I am getting token keyerror

### ISSUE THREAD

**Issue by ren276** [TejasNair9977/lubit#12]
**Describe the bug**

**To Reproduce**
1. After running the music_bot py , the error is coming

**Expected behavior**
Bot should run

**Comment by TejasNair9977** [comment]
@ren276  The bot works completely fine, you just need to do a few things before being able to run it.
I recommend you to take a look at this link:-
[Discord Bot Tokens](https://www.writebots.com/discord-bot-token/)
If you're working on the project locally, simply replace 
`os.environ['TOKEN']`
in the very last line, with the token you got from the above link, like so.
`bot.run("YOUR_TOKEN")`
Then you should be able to run the bot without any issues.
I also recommend you to read about .env files for security reasons.
# Important
If you ever decide to push the code, make sure to replace the last line to `bot.run(os.environ['TOKEN'])`, since if anyone gets access to your token, they can take control of your bot.

**Comment by TejasNair9977** [comment]
I added a bit more info in the README.md file so that it's easier to understand and run for everyone. Thanks for taking interest in this project!

**Comment by ren276** [comment]
Yeaa sure I will look into it !!
